duckie-team/duckie-android

- data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/data2domain.kt
- data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/domain2data.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/Heart.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/Report.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/chat.kt
> refactor: 모델 변경 사항 반영

- domain/build.gradle.kts
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/DuckFetchRepository.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/result/DuckApiResult.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchAllFeedsUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchChatReadUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchChatRoomsUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchCommentsUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchFollowUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchHeartUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchRecommendationFeedsUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchReviewUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchSaleRequestsUseCase.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/cache/CacheHolder.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/upsert/UpsertUserUseCase.kt
- 캐싱 기능 도입
- 의존되는 테이블은 상황에 따라 같이 생성하도록 설정
- 피드 정보와 좋아요 정보를 같이 반환하도록 개선
> feat: improve usecase

- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/DuckAssertRepository.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/assert/CheckNicknameAvailableUseCase.kt
- 닉네임 사용 가능 여부 확인을 위한 DuckAssertRepositoy 추가
> feat: 닉네임 사용 가능 여부 API 추가

- data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/HeartData.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/Heart.kt
- domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/constraint/HeartTarget.kt
- Heart 전체 미지원 -> HeartTarget.Comment 만 지미원
> feat: Heart 에서 잘못된 Unsupported 범위 조정

- data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/DuckAssertRepositoryImpl.kt
- DuckAssertRepositoryImpl#checkNicknameAvailable 추가
> feat: DuckAssertRepositoryImpl 구현

- .editorconfig
- .gitignore
- CNAME
- LICENSE
- detekt-config.yml
- gradle.properties
- renovate.json
- lint 구성 파일 최신화
- renovate 구성 업데이트
- 빌드 옵션 최적화
> feat: 구성 파일 업데이트

- build-logic/build.gradle.kts
- build-logic/gradle.properties
- build-logic/settings.gradle.kts
- build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
- build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
- build-logic/src/main/kotlin/DependencyGraphPlugin.kt
- build-logic/src/main/kotlin/JvmDokkaPlugin.kt
- build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/compose.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
- settings.gradle.kts
- Gradle Convention Plugins 을 도입하였습니다.
> chore: gradle convention plugins 도입

- app/build.gradle.kts
- app/src/androidTest/kotlin/team/duckie/app/android/ExampleInstrumentedTest.kt
- app/src/main/AndroidManifest.xml
- app/src/test/kotlin/team/duckie/app/android/ExampleUnitTest.kt
- settings.gradle.kts
> feat: app 모듈 추가

- feature-datastore/build.gradle.kts
- feature-datastore/src/androidTest/kotlin/team/duckie/app/android/feature/datastore/ExampleInstrumentedTest.kt
- feature-datastore/src/main/AndroidManifest.xml
- feature-datastore/src/main/kotlin/team/duckie/app/android/feature/datastore/DataStore.kt
- feature-datastore/src/test/kotlin/team/duckie/app/android/feature/datastore/ExampleUnitTest.kt
- feature-ui-onboard/build.gradle.kts
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- presentation/build.gradle.kts
- presentation/src/main/kotlin/team/duckie/app/android/presentation/MainActivity.kt
- settings.gradle.kts
- util-ui/build.gradle.kts
- util-ui/src/androidTest/kotlin/team/duckie/app/android/util/ui/ExampleInstrumentedTest.kt
- util-ui/src/main/AndroidManifest.xml
- util-ui/src/main/kotlin/team/duckie/app/android/util/ui/BaseActivity.kt
- util-ui/src/test/kotlin/team/duckie/app/android/util/ui/ExampleUnitTest.kt
- util-viewmodel/build.gradle.kts
- util-viewmodel/src/androidTest/kotlin/team/duckie/app/android/util/viewmodel/ExampleInstrumentedTest.kt
- util-viewmodel/src/main/AndroidManifest.xml
- util-viewmodel/src/test/kotlin/team/duckie/app/android/util/viewmodel/ExampleUnitTest.kt
- `feature-datastore`, `feature-util-ui`, `feature-util-viewmodel` 모듈 추가
> feat: 유틸 모듈들 추가

- app/build.gradle.kts
- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
- build-logic/src/main/kotlin/AndroidHiltPlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
- buildSrc/src/main/kotlin/ConventionEnum.kt
- 편한 Hilt 구성을 위한 hilt convention 추가
> chore: androidHiltPlugin 추가

- build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
- build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
- build-logic/src/main/kotlin/AndroidHiltPlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
- build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
- build-logic/src/main/kotlin/DependencyGraphPlugin.kt
- build-logic/src/main/kotlin/JvmDokkaPlugin.kt
- build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/compose.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
- project dependnecy graph 구현 업데이트
- 코드 스타일 개선
> refactor: build-logic 재정비

- util-viewmodel/build.gradle.kts
- util-viewmodel/src/main/kotlin/team/duckie/app/android/util/viewmodel/BaseViewModel.kt
- BaseViewModel 의 기초 구현을 상록님의 코드를 참고하여 추가하였습니다.
> feat: BaseViewModel 기초 작업

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/DependencyGraphPlugin.kt
- build-logic/src/main/kotlin/JvmLibraryPlugin.kt
- build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
- buildSrc/src/main/kotlin/ConventionEnum.kt
- gradle/libs.versions.toml
- settings.gradle.kts
- util-kotlin/build.gradle.kts
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/DuckieDsl.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/FastList.kt
- util-kotlin/src/test/kotlin/team/duckie/app/android/util/kotlin/ExampleUnitTest.kt
- 안드로이드 프레임워크에 의존성이 없어 도메인 모듈에서도 활용할 수 있는 순수 코틀린 유틸 모듈을 추가했습니다.
> feat: util-kotlin 추가

- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/common/OnboardTopAppBar.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/CategoryScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/TagScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/screen/IntroScreen.kt
- 수정 요청 사항 중 일부를 반영하였습니다.
- 온보딩 상태가 업데이트되지 않던 버그를 해결하였습니다.
> Fix state bug

- .github/workflows/android-ci.yml
- .github/workflows/auto-approve.yml
> feat: CI 설정

- feature-ui-home/build.gradle.kts
- feature-ui-onboard/build.gradle.kts
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/common/OnboardTopAppBar.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/2_CategoryScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- gradle/libs.versions.toml
- 태그 부분을 FlowRow 로 변경하였습니다.
- 건너뛰기 기능을 제거하였습니다.
> feat: 온보딩 UI 변경사항 반영

- data/src/main/kotlin/team/duckie/app/android/data/user/repository/UserRepositoryImpl.kt
- di/src/main/kotlin/team/duckie/app/android/di/usecase/user/UserUseCaseModule.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/repository/UserRepository.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/GetUserUseCase.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/UserNicknameValidateCheckUseCase.kt
이 작업 이후로는 백앤드 노션 문서 갱신 후 작업 예정입니다.
- GET /users/$id
- GET /users/$nickname/dupliate-check
> API 현황 점검 및 구현 2차

- data/src/main/kotlin/team/duckie/app/android/data/auth/repository/AuthRepositoryImpl.kt
- feature-ui-onboard/build.gradle.kts
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt
> feat: 온보딩 API 최종 연결

- app/src/main/kotlin/team/duckie/app/android/App.kt
- buildSrc/build.gradle.kts
- buildSrc/gradle.properties
- buildSrc/src/main/kotlin/PluginDependenciesSpecExtensions.kt
- data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
- data/src/main/kotlin/team/duckie/app/android/data/_exception/util/responseCatching.kt
- data/src/main/kotlin/team/duckie/app/android/data/auth/repository/AuthRepositoryImpl.kt
- data/src/main/kotlin/team/duckie/app/android/data/user/mapper/data2domain.kt
- data/src/test/kotlin/team/duckie/app/android/data/ExceptionTest.kt
- domain/build.gradle.kts
- domain/src/main/kotlin/team/duckie/app/android/domain/auth/usecase/CheckAccessTokenUseCase.kt
- feature-photopicker/src/main/kotlin/team/duckie/app/android/feature/photopicker/PhotoPicker.kt
- feature-ui-onboard/build.gradle.kts
- feature-ui-onboard/src/main/AndroidManifest.xml
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/constant/OnboardStep.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- plugin-ktor-client/src/main/kotlin/team/duckie/app/ktor/client/plugin/DuckieAuthorizationHeaderOrNothingPlugin.kt
- plugin-ktor-client/src/test/kotlin/team/duckie/app/ktor/client/plugin/e2e_test/DuckieAuthorizationHeaderOrNothingTest.kt
- presentation/build.gradle.kts
- presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/IntroViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/PresentationViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/sideeffect/IntroSideEffect.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/state/IntroState.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/state/PresentationState.kt
- presentation -> intro 로 명명을 통일했습니다.
- IntroViewModel 에 SavedStateHandle 지원을 추가했습니다.
- IntroViewModel 을 재구현했습니다.
- API 스펙과 다른 로직을 수정하였습니다.
- 온보딩 finish 상태가 일치하지 않던 버그를 해결하였습니다.
> feat: 온보딩 런타임 예외 해결

- app/build.gradle.kts
- data/build.gradle.kts
- data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationClient.kt
- data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
- data/src/main/kotlin/team/duckie/app/android/data/_datasource/FuelClient.kt
- data/src/main/kotlin/team/duckie/app/android/data/auth/repository/AuthRepositoryImpl.kt
- data/src/main/kotlin/team/duckie/app/android/data/file/repository/FileRepositoryImpl.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- gradle/libs.versions.toml
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/AllowMagicNumber.kt
- 파일 업로드가 작동하지 않던 버그 해결 (+ HttpClient 변경 (#180))
- 불필요한 로딩 UI 제거
> feat: 온보딩 파일 업로드 버그 수정

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieTodoScreen.kt
- shared-ui-compose/src/main/res/values/strings.xml
- 홈 화면에서 특정 탭 누를 시 Crash 나는 것이
개발 과정에서 귀찮을 때가 많아 해당 화면을 만들었습니다.
<image src=https://user-images.githubusercontent.com/13694046/213874157-0f14a18f-dca1-46d3-b8b4-9d03817f80b6.png width=360>
> 추후 개발 화면(DuckieTodoScreen) 생성

- data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/CreateProblemBottomLayout.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt
#171 에 언급된 리뷰 내용을 반영했습니다.
1. toPersistentList -> toImmutableList
2. `::` 을 활용하여, quackClickable, fastMap 소괄호로 처리
3. FadeAnimatedVisibility -> QuackAnimatedVisibility
> #171 추가 리뷰 반영

- data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
- data/src/main/kotlin/team/duckie/app/android/data/_util/json.kt
- data/src/main/kotlin/team/duckie/app/android/data/tag/repository/TagRepositoryImpl.kt
- data/src/main/kotlin/team/duckie/app/android/data/user/mapper/data2domain.kt
- data/src/main/kotlin/team/duckie/app/android/data/user/repository/UserRepositoryImpl.kt
- feature-datastore/src/main/kotlin/team/duckie/app/android/feature/datastore/DataStore.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/constant/OnboardStep.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
- feature-ui-onboard/src/main/res/values/strings.xml
- 유저 정보 수정 API 가 정상적으로 작동하지 않던 버그를 수정하였습니다.
> feat: 온보딩 작동 버그 해결

- feature-ui-detail/build.gradle.kts
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/DetailActivity.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/sideeffect/DetailSideEffect.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt
- feature-ui-detail/src/main/res/values/strings.xml
- feature-ui-home/build.gradle.kts
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
- util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
- 상세 화면 연결 로직을 초기 작성하였습니다.
- 상세 화면에 팔로우 로직을 적용했습니다.
---
홈 화면 작업과 겹쳐 conflict 가 우려됩니다.
해당 내용은 TODO 로 명세해 놓았습니다. (feat @limsaehyun)
> 상세화면 연결 로직 작성 & 상세화면에 팔로우 로직 연동

- data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
백앤드에서 "Authorization" 을 현재 사용하고 있습니다.
API 전반에 영향을 끼치는 내용이라, 아무래도 develop 에 빠른 반영이 필요해 보였습니다.
이 작업만 단일 PR 로 빠르게 작업하고 합칩니다 🙏
> feat: Authorization 헤더 key 값 변경

- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/DummyData.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/AnswerSection.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/choice/AnswerBox.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/common/LoadingIndicator.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/question/audio/Controller.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/sideeffect/SolveProblemSideEffect.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/state/SolveProblemState.kt
- util-kotlin/build.gradle.kts
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/list.kt
- 문제 풀기 feature에서 MVI 를 적용하였습니다.
- Size가 있는 ImmutableList를 만드는 Factory Function을 구현하였습니다 https://github.com/duckie-team/duckie-android/pull/206/commits/a76afcc381aae957b87741a256a1bea8dfcbd30b
- ImmutableList를 위한 Mutable Builder를 구현하였습니다.  https://github.com/duckie-team/duckie-android/pull/206/commits/5be6a71b52658ae496388a7e592e84e34d5bd7c6
- 위 두 사항으로 인해 `util-kotlin`에 immutable Collection 의존성을 추가하였습니다.
> 문제 풀기 MVI 적용

- gradle/libs.versions.toml
디버깅 브레이크 포인트가 안 걸리는 이슈가 있어 버전 롤백합니다.
> Android Studio Veresion 플라밍고8로 롤백

- data/src/main/kotlin/team/duckie/app/android/data/_exception/util/responseCatching.kt
- data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
- data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt
- data/src/main/kotlin/team/duckie/app/android/data/heart/mapper/mapper.kt
- data/src/main/kotlin/team/duckie/app/android/data/heart/model/HeartsData.kt
- data/src/main/kotlin/team/duckie/app/android/data/heart/repository/HeartsRepositoryImpl.kt
- data/src/main/kotlin/team/duckie/app/android/data/tag/repository/TagRepositoryImpl.kt
- data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
- di/src/main/kotlin/team/duckie/app/android/di/usecase/heart/HeartsUseCaseModule.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/heart/model/Hearts.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/heart/repository/HeartsRepository.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/heart/usecase/DeleteHeartsUseCase.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/heart/usecase/PostHeartsUseCase.kt
- feature-ui-detail/build.gradle.kts
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt
- 상세 화면에서 앱 유저 정보를 가져올 수 있도록 처리했습니다.
- 좋아요 API 변경에 대응한 작업을 수행했습니다.
- 기타 버그를 수정했습니다
- int 를 String 으로 처리한 내용
- Fuel 작업 체크 완료했습니다. 체크하면서 일부 코드를 수정했습니다.
- DELETE /heart 추가작업 필요합니다
> 요거 뒤에 heartId를 param으로 줘야하는데 문서를 잘못적어놨네요 :bowing:
> 상세 화면에 유저 연동 & 좋아요 response 변경 내역 반영

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ErrorScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt
- feature-ui-create-problem/src/main/res/values/strings.xml
- feature-ui-detail/build.gradle.kts
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
- shared-ui-compose/build.gradle.kts
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieCircularProgressIndicator.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/ErrorScreen.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/LoadingScreen.kt
- shared-ui-compose/src/main/res/values/strings.xml
로딩화면, 에러화면 디자인 가이드를 반영했습니다. (꽥꽥 미제공 기능은 TODO 작성했습니다)
`상세 화면`, `문제 만들기 화면`의 로딩, 에러 화면을 공통화했습니다.
> 로딩화면, 에러화면 공통화 1차

- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/ExamResultActivity.kt
- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/ExamResultScreen.kt
Result -> Main으로 갈 때 clearTop 적용
시험 결과에서 종료 버튼 X로 변경
> 시험 결과에서 화면 이동 처리

- .gitignore
- app/build.gradle.kts
- app/proguard-rules.pro
release app build 및 signing apk 추출을 위한 작업입니다.
---
고민
- R8 및 isMinifyEnabled 등의 기능을 활성화 할 수 없습니다.
```
ava.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at …
```
> signingConfig.properties 설정

- data/src/main/kotlin/team/duckie/app/android/data/examInstance/mapper/mapper.kt
- data/src/main/kotlin/team/duckie/app/android/data/examInstance/repository/ExamInstanceRepositoryImpl.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/examInstance/model/ExamInstance.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/examInstance/repository/ExamRepository.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
https://sungbinland.slack.com/archives/C04N46C0NQK/p1676965611313119?thread_ts=1676953134.906669&cid=C04N46C0NQK 에 근거합니다.
내용이 많지 않아서 확인 후 머지 부탁드리겠습니다.
@riflockle7 @jisungbin
> POST exam-instance 호출시 객체가 여러번 생성되는 문제 해결

- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/shortanswer/EachCharTextField.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/FlowLayout.kt
https://www.notion.so/jisungbin/10-57dd948ecd9642e29bea9678b910b68d?pvs=4
- FlowLayout을 구현하였습니다
> 문제 풀기에서 주관식 텍스트 필드가 10자가 넘어갈 때 스크롤 해야하는 현상

- .github/workflows/android-ci.yml
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
> resolve #265

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
https://www.notion.so/jisungbin/6391c099a7824baeabebdee8fceb68ae?pvs=4
> reslove #255

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
https://www.notion.so/jisungbin/4fcd757f33e349dfa7a572967e66583b?pvs=4
다양한 화면을 커버하기 위해, aspectRatio를 적용
https://user-images.githubusercontent.com/70064912/221519349-0df23305-7ca4-4542-8157-162a9246d0a3.mp4
> resolve #256

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckTestSmallCover.kt
https://www.notion.so/jisungbin/Rounded-corner-9ca2cbbef60847abac6779c8e74b4b99?pvs=4
---
> resolve #247

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/AnnotatedText.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/HashTag.kt
https://www.notion.so/jisungbin/DuckieOrange-b90cb3df60b4419cbeb6d31a12e79e61?pvs=4
b336b17b5f71c9cf19d0281b29153254f232e49c
- String을 조립할 수 있는 확장함수를 만들었습니다. 
- 해시태그를 앞에 붙이는 확장함수를 만들었습니다.
41bdfb1276ce9b9a4c55d57a900220ae39a33778
- QuackAnnotatedText를 임시로 사용할 수 있게 만들어 두었습니다.
https://user-images.githubusercontent.com/70064912/221576233-f8e97c18-91c4-40f1-98d4-572b8d973ad9.mp4
> resolve #249

- .github/workflows/android-ci.yml
resolve #281
시간 확인 후 actions/setup-java@v3 의 `cache: gradle` 도 지울지 생각중입니다.
> resolve #281

- data/src/main/kotlin/team/duckie/app/android/data/me/repository/MeRepositoryImpl.kt
- data/src/main/kotlin/team/duckie/app/android/data/user/mapper/data2domain.kt
- data/src/test/kotlin/team/duckie/app/android/data/JsonBuilderTest.kt
- data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/auth/usecase/CheckAccessTokenUseCase.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/model/User.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/model/UserStatus.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/GetMeUseCase.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/IntroViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/sideeffect/IntroSideEffect.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/exception.kt
resolve #260
---
에러를 뱉어줄까 생각했었는데, 일부 화면에서만 처리하면 될 것 같아 각 화면에서 처리하도록 했습니다.
모든 화면에서 NEW 를 캐치해야한다면 에러를 뱉어주도록 처리 예정입니다. (클라이언트 내부 code throw 예정)
exception 코드 관련 정리도 진행했습니다.
> resolve #260

- data/src/androidTest/kotlin/team/duckie/app/android/data/DbReadWriteTest.kt
- data/src/main/kotlin/team/duckie/app/android/data/kakao/repository/KakaoRepositoryImpl.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/ThirdPartyException.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
- close #259 
- DuckieThirdPartyException을 추가하였습니다.
- Kakao 같이, 자체적으로 Exception 처리 모델을 가지고 있는 경우, 덕키의 Exception으로 변환하여 Presentation에 내려주기 위해 만들게 되었습니다.(Presentation에서 Kakao 의존성을 가지지 않기 위함)
- 스크린샷에 토스트 메시지를 출력하였는데, 더 좋은 문구가 있다면 추천 부탁드립니다
> resolve #259

- app/build.gradle.kts
- data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/common/BottomBar.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/common/TopBar.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/navigator/impl/SolveProblemNavigatorImpl.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/navigator/module/SolveProblemNavigatorModule.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
- feature-ui-solve-problem/src/main/res/values/strings.xml
- feature-ui-start-exam/build.gradle.kts
- feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamActivity.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Dialog.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/FlowLayout.kt
> resolve #291 [시험 풀기 화면 개밥 먹기 1차]

- gradle/libs.versions.toml
관련 라이브러리 버전도 같이 업데이트
- plugin-kotlin-ksp
- kotlin-core
- kotlin-dokka
---
run 만 되도록 만든 상태여서 버그나 크래시가 있을 수도 있습니다
그건 각 작업자들이 발견하여 수정해주시면 되겠습니다.
> compose-runtime 을 "1.4.0-rc01" 으로 변경하면서 발생한 오류 수정

- .github/workflows/android-cd.yml
> feat: cd 초기 구축

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/DuckTestBottomNavigation.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
- feature-ui-home/src/main/res/values/strings.xml
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
> Feat/홈 화면 개밥먹기 1차 작업

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/navigator/impl/CreateProblemNavigatorImpl.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/navigator/module/CreateProblemNavigatorModule.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/HeadLineTopAppBar.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/HomeTopAppBar.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/RankingStep.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamSection.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamineeSection.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/dummy/SkeletonData.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/sideeffect/RankingSideEffect.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/state/RankingState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/viewmodel/RankingViewModel.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/dummy/SkeletonData.kt
- feature-ui-home/src/main/res/values/strings.xml
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckExamCoverItem.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Spacer.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/TextTabLayout.kt
> 명예의전당 Screen 및 dummy data

- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
- close #316 
- 검색에서 자신이 나오면 팔로잉을 할 수 없도록 버튼을 제거함
> resolve #316

- data/src/test/kotlin/team/duckie/app/android/data/ExamRepositoryTest.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/DetailActivity.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/sideeffect/DetailSideEffect.kt
- feature-ui-detail/src/main/res/values/strings.xml
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/navigator/impl/SearchNavigatorImpl.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/navigator/module/SearchNavigatorModule.kt
> resolve #290

- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/AnswerSection.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/sideeffect/SolveProblemSideEffect.kt
- close #321 
- close #293 
시험 문제 풀기에서 Crash 해결
가져온 시험 문제가 null일 경우 처리(edge case)
> solve #321, 293

- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
- feature-ui-onboard/src/main/res/values/strings.xml
resolve #285
아래 항목은 확인이 필요하여 다음에 작업 예정입니다.
- 꽥꽥 작업 후 전면 반영
- 사이즈랑 간격
- 텍스트 크기
- 발현되지 않음
- 온보딩 카카오 로그인 도중 카카오톡 없을 경우, 연결 프로그램 나옴
- 간헐적으로 카카오로그인 후 온보딩을 거치지 않음에도, 메인으로 바로 넘어가는 이슈
- 자세한 내용 확인 필요
- 닉네임 입력이 안되어있을 때의 case 처리
> resolve #285

- gradle/libs.versions.toml
cause::
```
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~i65F6P3_dpW-cju-1yvDnA==/team.duckie.app.android-5L4Ri7RCv4d_sVojdqtgaA==/base.apk)
```
> fix: foundation 버전 롤백

- data/schemas/team.duckie.app.android.data._local.DuckieDatabase/1.json
- data/src/main/kotlin/team/duckie/app/android/data/_local/Database.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/sideeffect/SearchSideEffect.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
- close #391
- [슬랙 쓰레드 내용](https://sungbinland.slack.com/archives/C04N46C0NQK/p1679833805086699)
- 최근 검색어가 또 일부 유저에게 보이지 않는 오류가 발생했습니다. room version이 migration 되지 않이 발생하는 문제로 예상됩니다.
- 1 버전에서 exportSchema를 하지 못해 1 to 2 autoMigration를 진행하지 못해, 예전 branch로 들어가 1 버전의 schema를 가져오고 autoMigration 진행했습니다.
- 최근 검색에서 키보드가 내려가는 부분을 삭제했습니다.
> Resolve #361

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingExamScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
- feature-ui-home/src/main/res/values/strings.xml
- close #383 
- 팔로우한 유저 중에 덕력고사가 없을 경우 대응
> feat: 팔로우한 유저 중에 덕력고사가 없을 경우 대응

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt
- feature-ui-create-problem/src/main/res/values/strings.xml
- 텍스트 변경 (어떤 분야를 좋아하나요? → 어떤 `카테고리`를 좋아하나요?) -> 주석 수정
- 시험 제목, 설명 등 글자 제한 있는 컴포저블 대응 -> hint 추가
- 문제만들기 종료 팝업 디자인 가이드 반영 (제목, 내용 수정)
> 문제 만들기 개밥 1차

- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/DuckieBottomSheetDialog.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/ReportBottomSheetDialog.kt
시험 상세 상단 태그 클릭 이벤트 제공, 신고하기 bottomsheet 올라오는 문제 해결
> 시험 상세 상단 태그 클릭 이벤트 제공, 신고하기 bottomsheet 올라오는 문제 해결

- build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt
> chore: version 1.0.1 업그레이드

- presentation/build.gradle.kts
- presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/screen/IntroScreen.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/IntroViewModel.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/sideeffect/IntroSideEffect.kt
- presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/state/IntroState.kt
- presentation/src/main/res/values/strings.xml
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/constant/Constant.kt
- shared-ui-compose/src/main/res/values/strings.xml
- util-android/src/main/kotlin/team/duckie/app/android/util/android/intent/IntentUtils.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
- util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/exception.kt
- API 작업이 필요합니다. (추후 commit 예정)
> 앱 업데이트 알림 화면 만들기 - (UI / API)

- feature-ui-home/src/main/AndroidManifest.xml
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainSideEffect.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainViewModel.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/ReportBottomSheetDialog.kt
- util-ui/src/main/kotlin/team/duckie/app/android/util/ui/BaseActivity.kt
- 메인 화면에 신고하기 기능을 작업했습니다.
- NavigationBar 색을 white로 바꾸었습니다. (BottomSheetDialog를 내리는 동안 NavigationBar에 보이는 현상 떄문)
> feat: 메인 화면에 신고하기 적용

- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
https://www.notion.so/duckie-team/c61aa1277ecc464b8fb0c27aefe547ff?pvs=4
기타
- 제가 왜 Issue 를 적었는지 이거 하면서 기억이 났네요
branch 네이밍이 복잡해서 이렇게 했었네요. 일단은 좀 더 지켜보는 걸로 하죠
> 온보딩 태그 선택 화면 태그 개수 유효성 체크 제거

- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsActivity.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/sideeffect/FriendsSideEffect.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
- util-compose/src/main/kotlin/team/duckie/app/android/util/compose/constraints.kt
- 친구 -> 프로필로 navigate 하는 기능을 구현했습니다.
- UserFollowingLayout을 리펙토링 하였습니다.
> feat: friend navigate 기능 구현

- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- [Issue Link](https://www.notion.so/duckie-team/ab2d2cbc27494ae0b0f9616725838fc0?pvs=4)
- 닉네임 중복 시 오류 방출
- 닉네임이 없을 경우 Next button invisible 처리
> fix: 회원가입 닉네임 중복검사 이슈 해결

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
- 온보딩 태그가 가려지는 현상 해결
https://www.notion.so/duckie-team/34d6a404e5fc4ac7bca1876fe1423585?pvs=4
> fix: 온보딩 태그가 가려지는 현상 해결

- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/QuizResultScreen.kt
- feature-ui-solve-problem/build.gradle.kts
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/QuizScreen.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/ScreenMeasurePolicy.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
- shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/LinearProgressBar.kt
- util-android/src/main/kotlin/team/duckie/app/android/util/android/timer/ProblemTimer.kt
- util-compose/src/main/kotlin/team/duckie/app/android/util/compose/PagerState.kt
타이머 기능을 구현하고, 프로그레스 바를 가지는 QuizScreen을 구현하였습니다.
https://user-images.githubusercontent.com/70064912/235342331-fb2e60f9-b8fe-4e2f-8cd1-2b5778c3a3da.mp4
- 프로그레스 바를 구현하였습니다.[200e8af](https://github.com/duckie-team/duckie-android/pull/446/commits/200e8af3fa211ab8e01f180c0f399ff1387ad9e5)
- 타이머를 구현하였습니다. [fa2abe8](https://github.com/duckie-team/duckie-android/pull/446/commits/fa2abe8b10c1dfed97848aba2cf3e242b4be060c)
> feat: Timer 구현 및 QuizScreen 구현

- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt
- feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
> 복원 - 문제 만들기에서 뒤로가기 시 다이얼로그에서 확인을 눌러도 바로 나가지지 않음(#439)

- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/ExamResultScreen.kt
- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/viewmodel/ExamResultState.kt
- feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/viewmodel/ExamResultViewModel.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/state/FriendsState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeViewModel.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageViewModel.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingViewModel.kt
- feature-ui-notification/src/main/kotlin/team/duckie/app/android/feature/ui/notification/screen/NoticationScreen.kt
- feature-ui-notification/src/main/kotlin/team/duckie/app/android/feature/ui/notification/viewmodel/NotificationState.kt
- feature-ui-notification/src/main/kotlin/team/duckie/app/android/feature/ui/notification/viewmodel/NotificationViewModel.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/state/ProfileState.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
- feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
- feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/state/SolveProblemState.kt
> 복원 - 에러 페이지 대응 (#447)

- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsActivity.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
- feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/state/FriendsState.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainSideEffect.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainViewModel.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileSideEffect.kt
- util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
- https://www.notion.so/duckie-team/navigate-f154efcd678f4e63ba8c7e29400c680d?pvs=4
- OtherProfile에서도 닉네임 부분에 나의 닉네임이 출력되는 현상 해결
* 리젝 사유에 있는 출제한 덕력고사 관련은 [다른 이슈](https://www.notion.so/duckie-team/OtherProfile-a6f8b31237154115a40af50af9cdff37?pvs=4)로 분리하였습니다
> fix: 친구 화면에서 닉네임이 잘못 출력되는 현상

- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
- feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
- feature-ui-onboard/src/main/res/values/strings.xml
- [close #ISSUE_NUMBER](https://www.notion.so/duckie-team/ab2d2cbc27494ae0b0f9616725838fc0?pvs=4)
- 디자인과 Writing 일치하게 변경
- 닉네임이 Empty 경우도 에러 메시지 출력하도록 대응
> fix: 회원가입 닉네임 Writing

- feature-ui-detail/build.gradle.kts
- feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
- util-compose/src/main/kotlin/team/duckie/app/android/util/compose/constants.kt
https://www.notion.so/duckie-team/Thumbnail-6e4d0edaaf9a40c1996494d9087ffdbf?pvs=4
> 시험 상세 화면 Thumbnail 모서리 둥그렇게 변경 필요

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/ExamSection.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/FavoriteSection.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/ProfileSection.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
- close [[마이페이지] 로딩시 프로그레스바 좌상단에 있음](https://www.notion.so/duckie-team/ffe9e030fb384bd792450440dd17fdf2?pvs=4)
- 마이페이지 로딩 프로그레스바를 제거했습니다.
- 마이페이지에 스켈레톤 UI를 적용했습니다.
- 프로필에 스켈레톤 UI를 적용했습니다.
> feat: 마이페이지, 프로필 스켈레톤 UI 처리

- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
https://www.notion.so/duckie-team/OtherProfile-a6f8b31237154115a40af50af9cdff37?pvs=4
- 출제한 덕력고사 부분이 Empty 처리 되어있었고, Composable과 데이터를 제공하여 해결
> Profile에서 출제한 덕력고사가 나오지 않는 버그 수정

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideFeatureScrren.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideScreen.kt
https://www.notion.so/duckie-team/0d9ca8e6900144a9b3f5a48042f30249?pvs=4
- skip 부분만 Pager에서 분리하였습니다.
https://github.com/duckie-team/duckie-android/assets/70064912/fdc80f35-1a02-4de9-8885-38b5cbbdb7a3
> 가이드 화면 건너뛰기가 매 페이지마다 같이 바뀌는 문제 해결

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamSection.kt
- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
- close [[명예의 전당] 시험 더보기 버튼 눌렀을 때 동작 안함](https://www.notion.so/duckie-team/059142d4b0144cb8a54af958bb4762a5?pvs=4)
- 명예의 전당에 신고하기 기능을 구현했습니다.
> feat: 명예의 전당 신고하기 기능 구현

- feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
- feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
https://github.com/duckie-team/duckie-android/pull/493#issue-1715007273
에서, 다른 유저 프로필에서 패딩이 이상하게 보이는 문제를 수정해였습니다.
> 다른 유저 프로필에서 패딩이 이상한 문제 해결

- feature/home/build.gradle.kts
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/constants/MainScreenType.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/MainScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/home/HomeRecommendFollowingExamScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/home/HomeRecommendFollowingScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/home/HomeScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/mypage/MypageScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/RankingScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/search/SearchMainScreen.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/viewmodel/MainViewModel.kt
- gradle/libs.versions.toml
ticket link: https://www.notion.so/duckie-team/GNB-3b6f458ebef042f7abff2f955be69606?pvs=4
> GNB 클릭시 각 페이지 로딩되는 현상 + 각 화면에 swipeRefresh 추가

- feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/viewmodel/ProfileViewModel.kt
- close [유저차단 기능 구현하기](https://www.notion.so/duckie-team/8a23a3b122814fbf92009715107f3ab8?pvs=4)
- Reject 이슈 해결
- 유저차단 성공 시 activity finish 처리
> feat: 차단에 성공했을 경우 activity finish 처리

- common/android/src/main/kotlin/team/duckie/app/android/common/android/ui/const/Extras.kt
- data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
- data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt
- feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/DetailActivity.kt
- feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/viewmodel/DetailViewModel.kt
- feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/viewmodel/sideeffect/DetailSideEffect.kt
- feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/quiz/StartQuizInputScreen.kt
- feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamState.kt
- feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamViewModel.kt
https://www.notion.so/duckie-team/754617af4b954bd592c22783ee155e7b?pvs=4
- Exam Model의 property를 추가하였습니다.
- requirementQuestion
- requirementPlaceholder
- timer
> 덕퀴즈 시작 화면에서 문제 당 주어지는 시간, 도전 조건이 피그마 스펙에 맞게 보여져야 함 

- feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/quiz/StartQuizInputScreen.kt
- feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamViewModel.kt
- quiz에서 필적확인문구를 입력해야만 입력이 가능했던 부분을 수정하였습니다.
> quiz랑 exam 로직이 같이 적용되는 부분 수정

- data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/BottomBar.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
https://github.com/duckie-team/duckie-android/pull/523#discussion_r1216102371
리뷰 반영 하지 않은채로 머지했음..
> Revert "덕퀴즈 답안 입력하지 않았을 시 다음 문제로 넘어가지 못하도록 변경"

- data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/BottomBar.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
Issue
https://www.notion.so/duckie-team/1a9e8811727e4b5f8e42cb7d8ba8a681?pvs=4
Overview (Required)
답안을 입력하지 않았을 때의 버튼 디자인을 변경하고, 다음으로 넘어가지 못하도록 변경하였습니다.
> 덕퀴즈 답안 입력하지 않았을 시 다음 문제로 넘어가지 못하도록 변경

- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/BottomBar.kt
덕퀴즈 첫 문제에서 제출하기 버튼으로 보이는 버그 수정
> 덕퀴즈 첫 문제에서 제출하기 버튼으로 보이는 버그 수정

- data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
- feature/skeleton/build.gradle.kts
- feature/skeleton/src/main/AndroidManifest.xml
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/SkeletonActivity.kt
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/navigator/impl/SkeletonNavigatorImpl.kt
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/navigator/module/StartExamNavigatorModule.kt
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/viewmodel/SkeletonViewModel.kt
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/viewmodel/viewmodel/sideeffect/StartExamSideEffect.kt
- feature/skeleton/src/main/java/team/duckie/app/android/feature/skeleton/viewmodel/viewmodel/state/StartExamState.kt
- feature/skeleton/src/main/res/values/strings.xml
- navigator/src/main/kotlin/team/duckie/app/android/navigator/feature/skeleton/SkeletonNavigator.kt
- settings.gradle.kts
앞으로 Activity 모듈을 만들 경우 `feature:skeleton` 모듈을 복사 붙여넣기 한 뒤
build.gradle.kts STEP 에 명세한대로 작업하면, 쉽게 Activity 모듈을 추가할 수 있습니다.
> Activity 모듈 스켈레톤(= 템플릿) 생성

- data/src/main/kotlin/team/duckie/app/android/data/quiz/model/PatchQuizBody.kt
- data/src/main/kotlin/team/duckie/app/android/data/quiz/repository/QuizRepositoryImpl.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/quiz/repository/QuizRepository.kt
- domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/SubmitQuizUseCase.kt
- feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/ExamineeSection.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/SolveProblemActivity.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/viewmodel/SolveProblemViewModel.kt
- feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/viewmodel/sideeffect/SolveProblemSideEffect.kt
> patch quiz에 wrongAnswer 전달

- build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt
- close #ISSUE_NUMBER
- 
| Before | After |
| :--: | :--: |
| <img src="" width="300" /> | <img src="" width="300" /> |
> chore: app version 1.1.0 update
