settings.gradle.kts
- 7일동안 한 번도 사용되지 않은 그레이들 캐시는 자동 삭제하도록 설정
=> chore: 빌드 캐시 자동 삭제 활성화

data/build.gradle.kts, data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamRequest.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamResponse.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ProblemItemData.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/repository/ExamRepositoryImpl.kt, data/src/main/kotlin/team/duckie/app/android/data/user/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/user/model/UserData.kt, di/build.gradle.kts, di/src/main/kotlin/team/duckie/app/android/di/datasource/NetworkModule.kt, di/src/main/kotlin/team/duckie/app/android/di/repository/ExamRepositoryModule.kt, di/src/main/kotlin/team/duckie/app/android/di/usecase/exam/ExamUseCaseModule.kt, domain/build.gradle.kts, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/ExamParam.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/ProblemItem.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Tag.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/repository/ExamRepository.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/usecase/MakeExamUseCase.kt, domain/src/main/kotlin/team/duckie/app/android/domain/user/model/User.kt, feature-ui-create-problem/build.gradle.kts, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/empty.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, gradle/libs.versions.toml, presentation/build.gradle.kts, presentation/src/main/AndroidManifest.xml
backend 세팅이 완료되지 않아 주석을 지우면 호출이 가능하도록 작성하였습니다
DI 
-  Ktor Client를 주입할 수 있는 Module 생성
-  Repository, Usecase Modeul 생성
Data
- model, repository, datasource 작성
Domain
- Usecase 작성
Presentation
- ui-create-problem 모듈에 viewModel로 더미 데이터 받아올 수 있도록 작성
=> 문제 만들기 API 추가

data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/repository/ExamRepositoryImpl.kt, di/src/main/kotlin/team/duckie/app/android/di/datasource/NetworkModule.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/repository/ExamRepository.kt, feature-ui-create-problem/build.gradle.kts, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/FadeAnimatedVisibility.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/FindTagItem.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/FindExamAreaScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemStep.kt, feature-ui-create-problem/src/main/res/values/strings.xml, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt, gradle/libs.versions.toml, settings.gradle.kts, shared-ui-compose/src/main/java/team/duckie/app/android/shared/ui/compose/DuckieGridLayout.kt, util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/AllowMagicNumber.kt
- QuackTheme 적용
- 시험 영역 텍스트 필드와 Tag가 나타나는 부분 Fade Animation으로 자연스럽게 변경
- figma 디자인에 맞게 padding 수정
- 시험 영역 태그를 클릭하면 기존 값 사라지도록 변경
- 텍스트필드 글자 수 제한 적용
- 시험 영역 placeholder 개선하여 TextField로 유도하도록 변경
- 시험 영역 화면에서 이전 화면으로 돌아갔을 때, 스크롤 상태 유지
- 시험 영역 찾기 리스트에서 횡범위를 넓게 설정
- 키보드 done ime action 시 현재 텍스트를 시험 영역으로 설정
=> 문제 만들기 1단계 UX 개선

feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/FindExamAreaScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt, gradle/libs.versions.toml
- **꽥꽥 1.4.3 버전을 적용하였습니다**
- 필적 확인 문구 TextField를 새로운 꽥꽥 컴포넌트로 변경하였습니다
- 시험 영역 찾기에서 검색 도중 이전 화면에 갔다와도 커서가 유지되도록 변경하였습니다
- 시험 영역 placeholder를 피그마 요구사항에 맞게 변경하였습니다
- QuackSurface를 이용하여 **해당 화면에서만 쓰이는 MediumButton**을 만들었습니다.
=> 문제 만들기 1단계 UI/UX 변경사항 반영

data/build.gradle.kts, data/src/main/kotlin/team/duckie/app/android/data/_util/JsonBuilder.kt, data/src/main/kotlin/team/duckie/app/android/data/_util/KtorExtensions.kt, data/src/test/kotlin/team/duckie/app/android/data/e2e_test/BodyNegotiationTest.kt, data/src/test/kotlin/team/duckie/app/android/data/e2e_test/module/BodyResponseModule.kt, data/src/test/kotlin/team/duckie/app/android/data/e2e_test/util/ApplicationTestClientBuilder.kt, gradle/libs.versions.toml, plugin-ktor-client/build.gradle.kts
Body 를 항상 POJO 로만 제공하다가, `jsonBody()` 를 도입하면서 Plain-Text 로 제공하는 코드가 생겼습니다. Plain-Text 로 Body 를 제공하는 경우는 처음인지라 테스트 코드가 필요하다고 느꼈고, 이에 맞는 테스트 코드를 작성하였습니다.
BodyNegotiationTest 는 위 설명대로 다음과 같은 케이스를 assertion 합니다.
- POJO Body 와 Plain-Text Body 의 receive 결과가 동일해야 함
- Object Body 와 Plain-Text Body 의 receive 결과가 동일해야 함
현스님의 조언으론 서버에서 Body 는 Plain-Text 로 처리되기에 클라이언트에서 Body 를 보낼 때 직렬화를 어떻게 하냐가 중요하다고 하셨습니다.
이 테스트는 Ktor Client 가 Body 를 보낼 때 POJO 와 Plain-Text 모두 동일하게 처리하는지를 assertion 하여 `jsonBody()` 에 문제가 없음을 확신하기 위함입니다.
=> test: BodyNegotiation E2E 테스트 작성

.github/workflows/android-ci.yml, build-logic/local-enums/build.gradle.kts, build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt, build.gradle.kts, domain/build.gradle.kts, domain/src/main/kotlin/team/duckie/app/android/domain/category/model/Category.kt, domain/src/main/kotlin/team/duckie/app/android/domain/tag/model/Tag.kt, domain/src/main/kotlin/team/duckie/app/android/domain/user/model/User.kt, feature-ui-onboard/build.gradle.kts, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/constant/OnboardStep.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/2_CategoryScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt, feature-ui-onboard/src/main/res/values/strings.xml, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, util-android/build.gradle.kts, util-android/src/main/kotlin/team/duckie/app/android/util/android/lifecycle/RepeatOnCreated.kt, util-android/src/main/kotlin/team/duckie/app/android/util/android/savedstate/SaveableMutableStateFlow.kt, util-compose/src/main/kotlin/team/duckie/app/android/util/compose/visibility.kt, util-exception-handling/src/main/kotlin/team/duckie/app/android/util/exception/handling/reporter/toast.kt
- AS 버전을 Giraffe 로 올렸습니다.
- OnboardViewModel 에 SavedStateHandle 지원을 추가했습니다.
- State 와 SideEffect 을 재정의했습니다.
- JDK 업데이트로 MavenLocal 재배포가 필요합니다.
- JDK 빌드 확인을 위해 `./gradlew build` 가 검증되지 않은 상태로 CI 돌립니다.
- 아직 런타임 검증을 하지 않았습니다. PR 범위를 줄이기 위해 먼저 올리고, 머지된 이후에 런타임 검증에 들어갑니다.
=> [MAJOR] feat: OnboardViewModel 재구현

feature-ui-start-exam/build.gradle.kts, feature-ui-start-exam/src/main/AndroidManifest.xml, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamActivity.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamScreen.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/viewmodel/StartExamSideEffect.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/viewmodel/StartExamState.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/viewmodel/StartExamViewModel.kt, feature-ui-start-exam/src/main/res/values/strings.xml, presentation/build.gradle.kts, presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt, settings.gradle.kts, shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieTodoScreen.kt, util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
1. 추후 화면의 백그라운드 색상을 설정했습니다 (흰색)
2. 모듈 추가를 해보면서 시험 시작 화면을 추가했습니다
3. Intent.Extra Key 값을 모아두는 곳을 만들었습니다.
해당 파일 위치가 괜찮은지, 관리 방식은 괜찮은지도 comment 부탁드립니다
4. placeholder 가 안 없어지는 TextField 가 필요하여 따로 만들었습니다.
해당 파일은 추후 꽥꽥으로 들어가야 할 것 같습니다.
---
1. 바로 시험 시작 화면을 향하면 오류가 발생합니다.
ExamId 와 CertifyingStatement 를 extra 로 넘겨주어야 동작합니다.
```kotlin
// ex
.apply {
putExtra(Extras.ExamId, 3)
putExtra(Extras.CertifyingStatement, "abcd")
}
```
2. 추후 extras 를 넣어야 할 경우를 대비한 startActivity 유틸 함수도 있으면 좋을 것 같다는 생각을 했습니다.
`startActivityForResult` 와 requestCode, resultCode 를 생각하면, 그냥 자체 구현이 좋을지도 생각이 드네요
=> 시험 시작 화면 UI 및 데이터 연동

data/src/main/kotlin/team/duckie/app/android/data/search/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/search/model/SearchData.kt, data/src/main/kotlin/team/duckie/app/android/data/search/repository/SearchRepositoryImpl.kt, data/src/test/kotlin/team/duckie/app/android/data/SearchRepositoryTest.kt, data/src/test/kotlin/team/duckie/app/android/data/dummy/SearchDummyResponse.kt, domain/src/main/kotlin/team/duckie/app/android/domain/search/model/Search.kt, feature-ui-create-problem/build.gradle.kts, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt, util-android/src/main/kotlin/team/duckie/app/android/util/android/image/MediaUtil.kt
- 단일 비트맵 가져오는 로직을 작성했습니다 (bitmap 최적화 포함)
- GET /search 작업을 수행했습니다
- `TAGS` 케이스를 추가했습니다
- type 을 대문자로 처리해야 하는 내용 반영했습니다.
- 문제 만들기 화면에 위의 내용들을 적용하였습니다. ( + 동시에 index 오류가 있어 수정했습니다)
- 이미지 업로드 로직을 추가함에 따라, `API 요청 로직`과 `state 설정 로직`을 분리했습니다.
분리하면서 이젠 server 로부터 받은 URL 을 적용하도록 했습니다.
- debounce 를 활용하여 입력 후 1.5초 뒤에 태그 검사를 하도록 처리했습니다.
---
- 맨 처음 PR 에서도 언급했지만 CreateProblemViewModel 중복 코드가 있을 것 같네요.
1차 완료 후 2단계 화면 개선 작업하면서 이 작업도 최대한 해보겠습니다.
=> 문제 만들기 화면 작업 (이미지 업로드, 태그 검색 로직 반영)

di/src/main/kotlin/team/duckie/app/android/di/usecase/exam/ExamUseCaseModule.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/usecase/GetExamUseCase.kt, feature-ui-create-problem/build.gradle.kts, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ErrorScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/LoadingScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemStep.kt, feature-ui-create-problem/src/main/res/values/strings.xml, feature-ui-home/build.gradle.kts, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
- 문제 만들기 화면 연결 로직을 초기 작성하였습니다.
- 문제 만들기 화면에 수정모드를 적용하였습니다.
- 로딩화면, 에러 화면을 새로 만들었습니다. (이에 따른 나열 순서 및 숫자 값을 변경했습니다)
- ViewModel 에 초기화 로직(`initState`), CreateProblemState 에 `isEditMode` 값을 추가했습니다.
- 에러 핸들링 코드를 작성했습니다.
---
홈 화면 작업과 겹쳐 conflict 가 우려됩니다.
해당 내용은 TODO 로 명세해 놓았습니다. (feat @limsaehyun)
추후 400, 401, 404 와 같은 status 분류가 필요합니다.
이에 따라 `responseCatching()` 복원 및 추가 작업이 필요합니다.
이와 관련된 작업은 다음 PR 에서 진행하겠습니다.
=> 문제 만들기 연결 로직 작성 & 문제 만들기 화면에 수정모드 적용 및 초기 에러 연동

feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt, feature-ui-onboard/src/main/res/values/strings.xml, util-compose/src/main/kotlin/team/duckie/app/android/util/compose/ToastWrapper.kt
- 온보딩 마무리 과정에서 태그 생성 실패 예외 대응을 추가하였습니다.
- ToastWrapper 에서 Toast 인스턴스의 메모리릭을 해결하였습니다.
=> 태그 생성 실패 대응

data/src/main/kotlin/team/duckie/app/android/data/tag/repository/TagRepositoryImpl.kt, feature-ui-create-problem/build.gradle.kts, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt
- 문제 만들기 화면에서 앱 유저 정보를 가져올 수 있도록 처리했습니다.
- 문제 만들기 도중 발생하는 오류를 수정하였습니다
- 문제 만들기를 실패해도 화면 종료하는 오류
- 카테고리 설정이 안되는 오류
- 에러 핸들링 로직 개선 (crash 없애기)
---
Fuel 작업이 merge 된 이후 동작 확인이 필요합니다. (그러니 절대 merge 하지 마세요)
https://github.com/duckie-team/duckie-android/issues/199 일부 내용을 반영 예정입니다.
=> 문제 만들기 화면에 유저 연동 & 문제 만들기 도중 발생하는 오류 수정

data/src/main/kotlin/team/duckie/app/android/data/_datasource/moshi.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamBodyData.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ProblemItemData.kt, data/src/main/kotlin/team/duckie/app/android/data/search/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/search/model/SearchData.kt, data/src/main/kotlin/team/duckie/app/android/data/search/repository/SearchRepositoryImpl.kt, data/src/test/kotlin/team/duckie/app/android/data/dummy/SearchDummyResponse.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/ExamBody.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt, domain/src/main/kotlin/team/duckie/app/android/domain/search/model/Search.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/CreateProblemBottomLayout.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/SearchTagScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mapper/mapper.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/solveproblem/DummyData.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/solveproblem/answer/AnswerSection.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/solveproblem/screen/SolveProblemScreen.kt, gradle/libs.versions.toml, util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/strings.kt
- 문제 만들기 화면에서 문제 만들 수 있도록 해놓았습니다. (백앤드 분들의 도움으로 문제를 찾을 수 있었습니다 🙇 )
- 불안정한 내용 태그 걸린 항목은 작업을 미뤘었는데, 검색의 경우엔 사용하는 곳이 꽤 많아 해당 내용 작업도 여기서 진행했습니다.
(별도로 분리하려 했는데 시간이 촉박할 듯 하여 일단 한 번에 작업 진행했습니다 🙏 )
- 기타 Moshi 적용, 백앤드 변경사항 미반영 내용 마저 반영했습니다.
=> 백앤드 반영 후 문제 만들기 화면 최종 확인 & 백앤드 연동 누락 내용 추가 (/search 및 Search 엔티티)

data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/CreateProblemBottomLayout.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
문제 만들기 오류를 수정했습니다
1. 5개 미만일 시 다음 화면으로 넘어가는 내용
2. 시험 시작 버튼 텍스트 유효성추가
3. 태그 검색결과 노출 수 수정 (4 -> 10개)
=> 문제 만들기 화면 오류 수정

feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
=> 문제 만들기 화면 태그 검색 결과 최대 개수 조정

data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt, domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/repository/RecommendationRepository.kt, domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchJumbotronsUseCase.kt, domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchRecommendationsUseCase.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendExamScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingExamScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/dummy/SkeletonData.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mapper/mapper.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
- close #325 
- 홈 팔로잉의 덕질고사 추천 페이지와 초기 팔로잉 추천 페이지를 다른 파일로 나누었습니다.
- 홈 화면의 팔로잉 탭에서 로딩이 제대로 작동되지 않아 고치면서 스켈레톤 UI도 적용했습니다.
- 홈의 로딩 상태와 PullToRefresh 상태가 동일하게 사용되어 초기에 PullRefreshIndicator가 나오는 현상을 둘의 상태를 분리해서 해결했습니다.
- PullRefresh 가 작동되도록 하였고, 사용자에게 새로고침이 됐음을 인지시키기 위해 최소한의 로딩 시간 (0.5초)를 적용했습니다.
=> resolve #325

data/src/main/kotlin/team/duckie/app/android/data/kakao/repository/KakaoRepositoryImpl.kt, domain/src/main/kotlin/team/duckie/app/android/domain/kakao/repository/KakaoRepository.kt, domain/src/main/kotlin/team/duckie/app/android/domain/kakao/usecase/GetKakaoAccessTokenUseCase.kt, util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
- close #326 
카카오톡이 설치되어 있을 때, 로그인이 되어있지 않다면 에러가 나는 문제를 해결했습니다.
https://devtalk.kakao.com/t/topic/128009
해당 이슈는 카카오에서 이미 진행 중인 이슈로 해당 오류가 발생 할 경우
카카오계정 로그인으로 처리되도록 개선하였습니다.
=> resolves #326

feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt, gradle/libs.versions.toml
- close #349 
compose-material에 ModalBottomSheetLayout 안에 있는 ScrollContainerInfo가 없어져
ModalBottomSheetLayout를 호출 할 경우 앱이 터지는 오류 발생
* compose-material 버전 업그레이드
=> Resolve #349

data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt, data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt
- close #378 
- 닉네임 중복 확인 API가 업데이트 되서, 온보딩이 동작하지 않는 오류 발생
- POST /user/duplicate-check 를 업데이트해서 해결
- KTor deprecated를 제거했습니다.
=> Resolve #378

feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
왜 직접 systemBarPaddings 변수를 코드에 언급해야 패딩이 적용되는지 이유를 알 수가 없네요 ㅇ_ㅇ
일단은 추가해두고 TODO 로 적어 놓았습니다.
=> OtherProfileScreen 접근 시 패딩이 적용되지 않는 오류 수정

data/build.gradle.kts, data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt, data/src/main/kotlin/team/duckie/app/android/data/_datasource/FuelClient.kt, data/src/test/kotlin/team/duckie/app/android/data/RegexTest.kt
관련 논의 쓰레드 : https://sungbinland.slack.com/archives/C043MKB4TJN/p1681916032300699
- 정규식을 활용하여 숫자값만 추출하였습니다. 
해당 값은 data 모듈 내에서 `BuildConfig.APP_VERSION_NAME_NUMBER` 으로 가져올 수 있습니다.
=> header 중에 x-duckie-version 값에 숫자만 들어가도록 처리

feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
- close #423 
- Kakao의 `NewUser` 정보를 통해서 기기당 온보딩(가이드)을 1회만 띄워주도록 변경
=> fix: 온보딩(가이드) 진입 조건 수정

feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt, feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
[QA Board](https://www.notion.so/duckie-team/73136a86eb834db592dfe00d7f868dea?pvs=4)
[Crashlytics](https://console.firebase.google.com/u/0/project/duckie-c3963/crashlytics/app/android:team.duckie.app.android/issues/80177b88d7e9f9588a77abea8b2a7b48?time=last-seven-days&sessionEventKey=643D193203E2000169900D6160D7A8F4_1801402733991545119)
- 카카오 로그인 시 crash가 발생하는 현상을 해결했습니다.
- profileImageUrl을 nullable로 처리해주었습니다.
=> fix: Kakao Login Crash

feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt, feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
https://www.notion.so/duckie-team/bf5461540b764085af10ea9058ed9dc4?pvs=4
이전 이슈에서 문제가 되었던 내용을 참고하여 문제 요소를 최대한 없앴습니다.
- Screen 에서는 sideEffect 를 post 하지 않도록 했습니다.
- 앱 종료 시 활용하는 SideEffect 방출은 viewModel 에서만 활용합니다
---
사실 이것도 완벽한 해결책은 아닙니다. (가끔 발현되는 걸 확인했습니다.)
하지만 일단 앱 차원에서 할 수 있는 최대한의 내용을 했습니다.
=> 문제 만들기에서 뒤로가기 시 다이얼로그에서 확인을 눌러도 바로 나가지지 않음

feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt, feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt, feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt, shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/quack/QuackNoUnderlineTextField.kt, shared-ui-compose/src/main/res/drawable/ic_textfield_delete_16.xml
- close https://www.notion.so/duckie-team/5fe5db1de9d34d72b2db7b92b5231a27?pvs=4
- padding 값이 QuackTextField 내부에 private으로 존재해서, QuackNoUnderlineTextField를 직접 구현했습니다.
- TextField에 Delete 아이콘을 추가했습니다.
- 검색 탭의 잘못된 padding값을 조정했습니다.
=> fix: 검색 탭 잘못된 padding 수정

app/build.gradle.kts, data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageSideEffect.kt, feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageViewModel.kt, feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt, feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt, feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/intent/MyPageIntent.kt, feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileSideEffect.kt, feature-ui-tag-edit/build.gradle.kts, feature-ui-tag-edit/src/main/AndroidManifest.xml, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/TagEditActivity.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/navigator/impl/TagEditNavigatorImpl.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/navigator/module/TagEditNavigatorModule.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/screen/TagEditScreen.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/viewmodel/TagEditSideEffect.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/viewmodel/TagEditState.kt, feature-ui-tag-edit/src/main/kotlin/team/duckie/app/android/feature/ui/tag/edit/viewmodel/TagEditViewModel.kt, feature-ui-tag-edit/src/main/res/values/strings.xml, navigator/src/main/kotlin/team/duckie/app/android/navigator/feature/tagedit/TagEditNavigator.kt, settings.gradle.kts, shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/FavoriteTagSection.kt, shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/screen/SearchTagScreen.kt, shared-ui-compose/src/main/res/values/strings.xml
notion ticket link: https://www.notion.so/duckie-team/35cad265c58141b0b991b7f24e01b334?pvs=4
1. 태그 편집 화면 기능을 만들었습니다.
2. 태그 추가 화면이 이곳 저곳에서 쓰일듯 하여 공통화 초기 작업을 수행했습니다.
추후 아래 화면에서 추가 작업 예정입니다.
- 문제 만들기 (1 / 3단계)
- 온보딩 화면 -> 이 화면은 고민중
3. 카테고리 추가 화면은 없어질 수도 있다고 해서 데이터만 만들어 놓았습니다.
---
이미 추가한 태그를 또 추가하는 경우 겹쳐 처리되었어서, 로직엔 문제가 없다고 판단했습니다.
이견이 있다면 comment 부탁드립니다.
=> 태그 편집 화면 구축 & 태그 추가 화면 공통화 초기 작업

data/src/main/kotlin/team/duckie/app/android/data/quiz/datasource/QuizDataSource.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/datasource/QuizRemoteDataSourceImpl.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/model/GetQuizResponse.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/model/PatchQuizBody.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/model/PostQuizResponse.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/repository/QuizRepositoryImpl.kt, di/src/main/kotlin/team/duckie/app/android/di/datasource/BindsModule.kt, di/src/main/kotlin/team/duckie/app/android/di/repository/BindsModule.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/Quiz.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizResult.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/repository/QuizRepository.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/GetQuizUseCase.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/MakeQuizUseCase.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/UpdateQuizUseCase.kt, domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/GetSearchUseCase.kt
덕퀴즈(챌린지) 생성 : https://www.notion.so/duckie-team/POST-challenges-7dd001df833c49948a7dfcd90b653963?pvs=4
덕퀴즈(챌린지) 정보 가져오기 : https://www.notion.so/duckie-team/GET-challenges-id-c251e373a58c42579ff19405e1b1ebb0?pvs=4
덕퀴즈(챌린지) 업데이트하기 : https://www.notion.so/duckie-team/PATCH-challenges-id-ea80cd7be6a14fd586473f0787523c40?pvs=4
=> challenge(quiz) API 구현

data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/QuizInfoResponse.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizInfo.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/BottomContent.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/DetailContent.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/TopCustomBar.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/MeasurePolicy.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/exam/ExamDetailScreen.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/quiz/QuizDetailScreen.kt, feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt, feature-ui-detail/src/main/res/values/strings.xml, shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieIcon.kt, shared-ui-compose/src/main/res/drawable/ic_crown_12.xml
- 시험상세 페이지에서 챌린지(퀴즈)와 덕력고사 분기 처리를 하였습니다.
- 챌린지(퀴즈)일 경우, 랭킹 표시되도록 변경하였습니다.
- ranking에 대한 정보가 없으면 보이지 않습니다
=> 시험상세 페이지 챌린지(퀴즈)와 덕력고사 분기 처리

feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamScreen.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/exam/StartExamInputScreen.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/quiz/StartQuizInputScreen.kt, feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/viewmodel/StartExamState.kt, feature-ui-start-exam/src/main/res/values/strings.xml
- `feature-ui-start-exam` 모듈에서, 시작 화면을 덕퀴즈와, 덕력고사로 분기하였습니다.
=> 덕퀴즈 시작 화면 구현

domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/AnswerSection.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/shortanswer/ShortAnswerForm.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/QuizScreen.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/state/SolveProblemState.kt, util-compose/src/main/kotlin/team/duckie/app/android/util/compose/PagerState.kt
- close [#문제 풀기 중 주관식 답안이 나오면 텍스트필드를 올리고, focus해줘야 함](https://www.notion.so/duckie-team/focus-82a89406e9a24e658028f497d870107e?pvs=4)
- 주관식 문제가 나올 경우 keyboard를 올려주었습니다.
- 주관식 문제가 나올 경우 정답 입력란에 focus를 request 해주었습니다.
* recomposition을 최적화 하던 도중 QuizScreen의 pageIndexed를 제거하였습니다. 추후 작업 시 참고부탁드립니다.
* QuizScreen 로직을 본의아니게 조금 건드리게 되었는데, 확인 한 번 부탁드립니다.
* HorizontalPager에서 페이지를 다 넘긴 후에 키보드를 올리기 위해서 key로 pagerState.currentPageOffsetFraction를 주었습니다. 때문에    recomposition이 많이 일어날 것 같은데 이렇게 처리를 해도 되는지 고민됩니다.
```kotlin
LaunchedEffect(pagerState.currentPageOffsetFraction) {
if (currentProblem.answer?.isShortAnswer() == true && pagerState.currentPageOffsetFraction == 0f) {
keyboardController?.show()
focusRequester.requestFocus()
} else {
keyboardController?.hide()
}
}
```
=> feat: 문제 풀기 주관식 문제 keyboard show, focus 처리

shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/screen/SearchTagScreen.kt
- close [태그 편집 → 태그 추가 화면 상단탭 디자인 안맞음](https://www.notion.so/duckie-team/6df798a8a2c54779a09fc21115cdaf88?pvs=4)
- 태그 추가 페이지의 상단탭 디자인을 수정했습니다.
- 태그 추가 페이지의 로직이나, 디자인이 전체적으로 다른 것 같습니다. 따로 [이슈화](https://www.notion.so/duckie-team/ad134c21e3e94ef493e8c3ad39012bb8?pvs=4) 해두었습니다.
=> fix: 태그 추가 화면 상단탭 페딩값 수정

data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt, presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt, presentation/src/main/kotlin/team/duckie/app/android/presentation/screen/IntroScreen.kt, presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/IntroViewModel.kt, presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/sideeffect/IntroSideEffect.kt, presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/state/IntroState.kt, presentation/src/main/res/values/strings.xml
notion ticket link: https://www.notion.so/duckie-team/7613e1c9e98a4291abb57e821f0a0279?pvs=4
팝업을 띄워주도록 했습니다.
기존에 띄워주는 팝업이 있어 enum 을 활용하여 처리했습니다.
=> 스플래쉬에서 진입 안 될 시 에러 핸들링 처리

domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/QuizScreen.kt, feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt, util-compose/src/main/kotlin/team/duckie/app/android/util/compose/PagerState.kt
- close [문제 풀기 중 주관식 답안이 나오면 텍스트필드를 올리고, focus해줘야 함](https://www.notion.so/duckie-team/focus-82a89406e9a24e658028f497d870107e?pvs=4)
- QuizScreen에 focusRequester 가 등록되지 않아 나타나는 오류 해결
=> fix: QuizScreen FocusRequester not Install

feature-photopicker/src/main/kotlin/team/duckie/app/android/feature/photopicker/PhotoPicker.kt
https://www.notion.so/duckie-team/94f3288942ff4816954fd489dd802277?pvs=4
- PhotoPicker에서 trailingicon 아래 화살표를 제거하였습니다.
=> 갤러리에서 전체보기 말고 다른 정렬 기준이 있는 것으로 착각하게 되는 현상 해결

feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt, feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
https://www.notion.so/duckie-team/2dbee991078b46f9acb834ce598f11a4?pvs=4
- 피그마 스펙에 맞게 관련 패딩값들을 수정하였습니다.
=> feat: figma 스펙에 맞게 패딩 값 수정

app/build.gradle.kts, app/src/main/kotlin/team/duckie/app/android/App.kt, data/build.gradle.kts, data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt, data/src/main/kotlin/team/duckie/app/android/data/file/repository/FileRepositoryImpl.kt, data/src/test/kotlin/team/duckie/app/android/data/CategoryRepositoryTest.kt, data/src/test/kotlin/team/duckie/app/android/data/ExamRepositoryTest.kt, data/src/test/kotlin/team/duckie/app/android/data/SearchRepositoryTest.kt, gradle/libs.versions.toml, plugin-ktor-client/build.gradle.kts, plugin-ktor-client/src/test/kotlin/team/duckie/app/ktor/client/plugin/util/LoggingHeadersPlugin.kt
release 에서도 로그가 남는다는 문제로 인해, println을 [Timber](https://github.com/JakeWharton/timber)로 대체하였습니다.
Timber를 사용하면 다음과 같은 이점이 있습니다.
- `Timber.e("message")` 형식으로 간단하게 사용할 수 있습니다.
- debug build에서만 로그를 확인할 수 있습니다.
=> logging 방식 변경

common/compose/build.gradle.kts, common/compose/src/main/kotlin/team/duckie/app/android/common/compose/typography.kt, common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/QuackMaxWidthDivider.kt, feature/setting/build.gradle.kts, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/component/SettingContentLayout.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/constans/SettingDesignToken.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingAccountInfoScreen.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingActivity.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingInquiryScreen.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingMainPolicyScreen.kt, feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingNotificationScreen.kt, gradle/libs.versions.toml
* close [feature-setting QuackQuackV2 로 바꾸기](https://www.notion.so/duckie-team/feature-setting-QuackQuackV2-728e9d07de214743956669de6219b259?pvs=4)
* 설정에서 마이그레이션 할 수 있는 부분을 마이그레이션 했습니다.
* 설정에서 일괄적인 규칙을 가진 디자인 토큰들을 SettingDesignToken으로 분리하여 관리했습니다.
* QuackQuack V1 to V2
=> refactor: feature-setting migrate quack-v2

feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/exam/StartExamInputScreen.kt, feature/start-exam/src/main/res/values/strings.xml
- close [시험 시작을 했더니 태그편집이 나오네…](https://www.notion.so/duckie-team/f44c7a1448bf44fca428bac561d4ba1f?pvs=4)
- 시험 시작 전 타이틀 텍스트 알맞게 변경
=> fix: 덕력고사 시작 전 타이틀 텍스트 변경

feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/SolveProblemActivity.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/answer/AnswerSection.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/answer/shortanswer/ShortAnswerForm.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/SolveProblemScreen.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/viewmodel/SolveProblemViewModel.kt
- close [덕력고사 간혈적인 Crash 발생](https://www.notion.so/duckie-team/Crash-131a6423771f422fb0e585c877ba4d19?pvs=4)
- 잦은 리컴포지션으로 인해 focusRequster가 초기화 되지 않아 crash가 발생했습니다.
- 필요한 경우에만 리컴포지션이 되도록 최적화를 진행했습니다.
- focusRequster에 대한 로직을 책임에 맞게 ShortAnswerForm으로 이동시켜 필요한 경우에만 요청할 수 있도록 로직을 재점검했습니다.
=> fix: 덕력고사에서 focusRequster가 초기화 되지 않는 오류

data/src/main/kotlin/team/duckie/app/android/data/quiz/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/quiz/model/GetQuizResponse.kt, domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizResult.kt, feature/exam-result/build.gradle.kts, feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/common/ResultBottomBar.kt, feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/screen/ExamResultScreen.kt, feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/screen/quiz/QuizResultContent.kt, feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/viewmodel/ExamResultState.kt, feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/viewmodel/ExamResultViewModel.kt, feature/exam-result/src/main/res/values/strings.xml
https://www.notion.so/duckie-team/c32f4855de244e3a853002f0f55911d5?pvs=4
- 결과 사진의 여백에 검정색 배경을 주었습니다.
- 해설 문구를 포함하였습니다(추후 꽥꽥 글꼴 추가될 시 변경 예정)
- 순위를 추가하였습니다.
=> 덕퀴즈 결과 화면 피그마 스펙에 맞게 수정

feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/exam/StartExamInputScreen.kt, feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/quiz/StartQuizInputScreen.kt, feature/start-exam/src/main/res/values/strings.xml
resolve [문제 시작 화면에 태그 편집 제목이 나옴](https://www.notion.so/duckie-team/4c760a52b98b4068976456a9c5f39a6c?pvs=4)
resource 중복으로 인한 오류를 수정하였습니다. (domain 이름을 prefix 로 추가)
---
당분간은 resource 네이밍 처리할 때, `key 이름에 prefix 를 필수`로 넣어야 될 것 같습니다.
(아래 사진 같이 모듈 별로 동일한 key 를 사용하면, 저 3개 중에 하나만 사용됩니다)
다른 해결책이 있는지는 좀 더 찾아봐야 되겠는데
nowinandroid 레포에서도 동일 현상이 발생해서요 ㅠ
일단은 저희 내부에서 주의가 필요해 보입니다.
---
참고) 아래 내용으로 try 해봤는데 전부 안되었습니다.
- 각 모듈 AndroidManifest.xml 에 package 속성값 추가하기
- R 을 풀 네이밍으로 사용하거나 as 를 활용해 사용하기
```kotlin
// 아래 케이스 모두 안됨
// 1
com.google.samples.apps.nowinandroid.feature.foryou.R.string.for_you
// 2
import com.google.samples.apps.nowinandroid.feature.foryou.R as forYouR
...
forYouR.string.for_you
```
=> 문제 시작 화면에 태그 편집 제목이 나옴

common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/BackPressedHeadLineTopAppBar.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/ProfileActivity.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/screen/MyProfileScreen.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/screen/OtherProfileScreen.kt
- close [마이페이지에 닉네임이 출력되지 않음](https://www.notion.so/duckie-team/45e15305d27b41c0a7ec30177ace3d8f?pvs=4)
- 마이페이지 닉네임이 출력되지 않는 오류를 개선했습니다.
- TopBar의 아이콘이 올바르게 배치되도록 수정했습니다. (다른 경로로 마이페이지에 진입 한 경우 ArrowBar 처리, 아이콘 위치 변경)
- BackPressedTopBar의 TrailingContent를 재사용 할 수 있도록 수정했습니다.
=> fix: 마이페이지 TopBar 디테일 잡기

feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/DetailContent.kt
- close [상세 화면에서 유저 프로필 사진 클릭시 프로필로 이동 안됨](https://www.notion.so/duckie-team/33c5fed09ed64263ad5280625b02669f?pvs=4)
- 홈 디테일에서 유저 프로필 클릭 범위는 프로필 사진을 포함하도록 변경했습니다.
=> fix: 홈 디테일 프로필 클릭 범위 수정

data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/BottomBar.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
- https://www.notion.so/duckie-team/1a9e8811727e4b5f8e42cb7d8ba8a681?pvs=4
답안을 입력하지 않았을 때의 버튼 디자인을 변경하고, 다음으로 넘어가지 못하도록 변경하였습니다.
=> 덕퀴즈 답안 입력하지 않았을 시 다음 문제로 넘어가지 못하도록 변경

feature/search/src/main/kotlin/team/duckie/app/android/feature/search/screen/SearchScreen.kt
- https://www.notion.so/duckie-team/17ddc93fda384036945ba5dce8210253?pvs=4
최근검색어 리플 범위 좌우 꽉차도록 변경
=> 최근검색어 리플 범위 변경

common/compose/src/main/res/values/strings.xml, common/kotlin/src/main/kotlin/team/duckie/app/android/common/kotlin/exception/constant.kt
- https://www.notion.so/duckie-team/4e780be0a8574c2ea8e2cd24c79cf36e?pvs=4
- 앱 업데이트 알림 예외가 ThirdPartyException으로 되어있어 변경하였습니다
- 앱 패키지 네임이 잘못되어 있던 문제를 해결하였습니다.
=> 앱 업데이트 알림이 나오지 않는 문제 해결

feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/ExamineeSection.kt
- https://www.notion.so/duckie-team/d19a4304b166428d8891e1c42a4950ec?pvs=4
명예의 전당 덕질 영역 태그 나오도록 변경 + 디폴트 이미지 추가
=> 명예의 전당 덕질 영역 태그 나오도록 변경 + 디폴트 이미지 추가

common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/UserFollowingLayout.kt, common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/icon/v1/DuckieIcon.kt, common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/icon/v2/DuckieIcon.kt, common/compose/src/main/res/drawable/ic_paper_20.xml, data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt, data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt, data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt, domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt, feature/detail/build.gradle.kts, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/DetailContent.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/exam/ExamDetailScreen.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/quiz/QuizDetailScreen.kt, feature/detail/src/main/res/values/strings.xml, feature/home/src/main/kotlin/team/duckie/app/android/feature/home/component/HomeTopAppBar.kt, feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/RankingScreen.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/screen/MyProfileScreen.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/screen/OtherProfileScreen.kt, feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/screen/section/ProfileSection.kt, feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/TopBar.kt
- https://www.notion.so/duckie-team/93419287906a4bdbb083c851cc05c332?pvs=4
- 총 문제수와, 응시자 수가 이제 덕력고사에서 출력됩니다
=> 총 문제수와, 응시자 수 덕력고사에서 보이도록 변경

data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt, feature/detail/build.gradle.kts, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/DetailActivity.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/BottomContent.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/DetailContent.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/common/TopCustomBar.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/DetailScreen.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/screen/quiz/QuizDetailScreen.kt, feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/viewmodel/state/DetailState.kt, feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/ExamineeSection.kt
resolve [시험 상세 서브태그 end쪽에 패딩 없애주기](https://www.notion.so/duckie-team/end-bc2d5450224c407792159260a214fa14?pvs=4)
- 이제 시험 상세 서브태그 우측에 패딩이 없어졌습니다.
- 상세 화면에 quack v2 를 적용하였습니다 (v1 은 제거했습니다)
- 변환해보니 빨간줄이 엄청 많네요. (import 및 QuackImage 적용 시 등등)
- QuackCircleTag 는 매치되는 내용을 한참 찾았네요. (style = `QuackTagStyle.Outlined` 을 적용하니 되었습니다)
- common.compose 에서 quack v1 을 쓰고 있어서 그런지 
./gradlew build 에서는 잡히지만, IDE 에선 안 보이는 컴파일 에러도 있네요 (빨간줄이 안보입니다)
```
Cannot access class 'kotlinx.collections.immutable.ImmutableList'. Check your module classpath for missing or conflicting dependencies
```
이건 추후 quack v1 을 걷어내면서 해소될 것 같네요
=> 시험 상세 서브태그 end쪽에 패딩 없애주기 및 상세화면에 quack v2 적용

common/compose/build.gradle.kts, common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/domain/DuckieTagAddBottomSheet.kt, common/compose/src/main/res/values/strings.xml, data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt, feature/home/src/main/kotlin/team/duckie/app/android/feature/home/screen/ranking/ExamineeSection.kt, feature/onboard/src/main/kotlin/team/duckie/app/android/feature/onboard/screen/3_TagScreen.kt, feature/onboard/src/main/kotlin/team/duckie/app/android/feature/onboard/viewmodel/OnboardViewModel.kt, feature/onboard/src/main/res/values/strings.xml, feature/search/src/main/kotlin/team/duckie/app/android/feature/search/viewmodel/SearchViewModel.kt, feature/tag-edit/src/main/AndroidManifest.xml, feature/tag-edit/src/main/kotlin/team/duckie/app/android/feature/tag/edit/screen/TagEditScreen.kt, feature/tag-edit/src/main/kotlin/team/duckie/app/android/feature/tag/edit/viewmodel/TagEditState.kt, feature/tag-edit/src/main/kotlin/team/duckie/app/android/feature/tag/edit/viewmodel/TagEditViewModel.kt
- close [태그 편집 > 직접 태그 추가 flow 개선](https://www.notion.so/duckie-team/flow-69419222e4c747709f401b28d871ed1a?pvs=4)
작업내용
- 태그 추가 바텀 시트 공통 Composable 를 만들었습니다.
- 태그 편집, 온보딩 화면에 적용하면서 태그 편집 화면에 직접 태그 추가 flow 개선도 같이 작업했습니다.
=> 태그 추가 바텀 시트 공통 Composable 추가 및 각 화면에 적용 (태그 편집, 온보딩)
